--SELECT TOP 50 *
--FROM msdb.INFORMATION_SCHEMA.ROUTINES
--WHERE ROUTINE_DEFINITION LIKE '%sparc_PSCompliance_FillTable%'

--SELECT TOP 50 *
--FROM msdb.INFORMATION_SCHEMA.ROUTINES
--WHERE ROUTINE_DEFINITION LIKE '%sparc_PSCompliance_FillTable%'
